name:                 haskell-conjunction
version:              0.1.0.0
visibility:           public
id:                   haskell-conjunction-0.1.0.0-inplace
key:                  haskell-conjunction-0.1.0.0-inplace
license:              BSD-3-Clause
maintainer:           sspeaks610@gmail.com
author:               Seth Speaks
abi:                  inplace
exposed:              True
exposed-modules:
    SGP4 SGP4.Bindings SGP4.Coordinate SGP4.Frames SGP4.Propagate
    SGP4.TLE SGP4.Time SGP4.Types

import-dirs:
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/build

library-dirs:
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/build

library-dirs-static:
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/build

dynamic-library-dirs:
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/build

data-dir:             /home/sspeaks/haskell-conjunction/.
hs-libraries:         HShaskell-conjunction-0.1.0.0-inplace
extra-libraries:      stdc++
include-dirs:
    /home/sspeaks/haskell-conjunction/cbits
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/build/cbits
    /home/sspeaks/haskell-conjunction/sgp4/cpp/SGP4/SGP4
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/build/sgp4/cpp/SGP4/SGP4

depends:
    base-4.20.2.0-1ba9 linear-1.23.2-8M4x3Gxm65LLxkAyd7Uga1
    time-1.12.2-5b0f

haddock-interfaces:
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/doc/html/haskell-conjunction/haskell-conjunction.haddock

haddock-html:
    /home/sspeaks/haskell-conjunction/dist-newstyle/build/aarch64-linux/ghc-9.10.3/haskell-conjunction-0.1.0.0/doc/html/haskell-conjunction
